-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 13:14:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema treage
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `treage` ;

-- -----------------------------------------------------
-- Schema treage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `treage` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `treage` ;

-- -----------------------------------------------------
-- Table `treage`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`ciudad` (
  `idCiudad` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreCiudad` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`tipocriterio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`tipocriterio` (
  `idTipoCriterio` INT(11) NOT NULL AUTO_INCREMENT,
  `TipoCriterio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoCriterio`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `treage`.`criterio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`criterio` (
  `idCriterio` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `tipocriterio_idTipoCriterio` INT(11) NOT NULL,
  PRIMARY KEY (`idCriterio`, `tipocriterio_idTipoCriterio`),
  INDEX `fk_criterio_tipocriterio1_idx` (`tipocriterio_idTipoCriterio` ASC) VISIBLE,
  CONSTRAINT `fk_criterio_tipocriterio1`
    FOREIGN KEY (`tipocriterio_idTipoCriterio`)
    REFERENCES `treage`.`tipocriterio` (`idTipoCriterio`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `treage`.`destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`destino` (
  `idDestino` INT(11) NOT NULL,
  `NombreDestino` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDestino`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`estado` (
  `idEstado` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreEstado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`hospital` (
  `idHospital` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreHospital` VARCHAR(45) NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` TINYINT(10) NULL DEFAULT NULL,
  `CP` TINYINT(5) NULL DEFAULT NULL,
  `Nivel` VARCHAR(10) NULL DEFAULT NULL,
  `TipoHospital` VARCHAR(15) NULL DEFAULT NULL,
  `estado_idEstado` INT(11) NOT NULL,
  `ciudad_idCiudad` INT(11) NOT NULL,
  PRIMARY KEY (`idHospital`),
  INDEX `fk_hospital_estado1_idx` (`estado_idEstado` ASC) VISIBLE,
  INDEX `fk_hospital_ciudad1_idx` (`ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_ciudad1`
    FOREIGN KEY (`ciudad_idCiudad`)
    REFERENCES `treage`.`ciudad` (`idCiudad`),
  CONSTRAINT `fk_hospital_estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `treage`.`estado` (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`rolusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`rolusuario` (
  `idRolUsuario` INT(11) NOT NULL,
  `NombreRol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idRolUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `rolusuario_idRolUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_rolusuario1_idx` (`rolusuario_idRolUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rolusuario1`
    FOREIGN KEY (`rolusuario_idRolUsuario`)
    REFERENCES `treage`.`rolusuario` (`idRolUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`hospital_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`hospital_has_usuario` (
  `hospital_idHospital` INT(11) NOT NULL,
  `usuario_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`hospital_idHospital`, `usuario_idUsuario`),
  INDEX `fk_hospital_has_usuario_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_hospital_has_usuario_hospital1_idx` (`hospital_idHospital` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_has_usuario_hospital1`
    FOREIGN KEY (`hospital_idHospital`)
    REFERENCES `treage`.`hospital` (`idHospital`),
  CONSTRAINT `fk_hospital_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `treage`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`tiempoatencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`tiempoatencion` (
  `idTiempoAtencion` INT(11) NOT NULL AUTO_INCREMENT,
  `HoraInicio` DATETIME(6) NULL DEFAULT NULL,
  `HoraFin` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`idTiempoAtencion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`medico` (
  `idMedico` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreMedico` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoPat` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoMat` VARCHAR(45) NULL DEFAULT NULL,
  `Matricula` VARCHAR(45) NULL DEFAULT NULL,
  `hospital_idHospital` INT(11) NOT NULL,
  `tiempoatencion_idTiempoAtencion` INT(11) NOT NULL,
  PRIMARY KEY (`idMedico`),
  INDEX `fk_medico_hospital1_idx` (`hospital_idHospital` ASC) VISIBLE,
  INDEX `fk_medico_tiempoatencion1_idx` (`tiempoatencion_idTiempoAtencion` ASC) VISIBLE,
  CONSTRAINT `fk_medico_hospital1`
    FOREIGN KEY (`hospital_idHospital`)
    REFERENCES `treage`.`hospital` (`idHospital`),
  CONSTRAINT `fk_medico_tiempoatencion1`
    FOREIGN KEY (`tiempoatencion_idTiempoAtencion`)
    REFERENCES `treage`.`tiempoatencion` (`idTiempoAtencion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`motivoatencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`motivoatencion` (
  `idMotivoAtencion` INT(11) NOT NULL,
  `DiagnosticoProb` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idMotivoAtencion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`procedencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`procedencia` (
  `idProcedencia` INT(11) NOT NULL,
  `NombreProcedencia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProcedencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`tipopaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`tipopaciente` (
  `idTipoPaciente` INT(11) NOT NULL,
  `TipoPaciente` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoPaciente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`paciente` (
  `idPaciente` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoPat` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoMat` VARCHAR(45) NULL DEFAULT NULL,
  `Sexo` VARCHAR(45) NULL DEFAULT NULL,
  `Edad` INT(11) NULL DEFAULT NULL,
  `Nss` VARCHAR(45) NULL DEFAULT NULL,
  `Numf` INT(11) NULL DEFAULT NULL,
  `FechaAtencion` DATETIME NULL DEFAULT NULL,
  `NivelUrgencia` VARCHAR(15) NULL DEFAULT NULL,
  `medico_idMedico` INT(11) NOT NULL,
  `destino_idDestino` INT(11) NOT NULL,
  `motivoatencion_idMotivoAtencion` INT(11) NOT NULL,
  `tipopaciente_idTipoPaciente` INT(11) NOT NULL,
  `procedencia_idProcedencia` INT(11) NOT NULL,
  PRIMARY KEY (`idPaciente`),
  INDEX `fk_paciente_medico1_idx` (`medico_idMedico` ASC) VISIBLE,
  INDEX `fk_paciente_destino1_idx` (`destino_idDestino` ASC) VISIBLE,
  INDEX `fk_paciente_motivoatencion1_idx` (`motivoatencion_idMotivoAtencion` ASC) VISIBLE,
  INDEX `fk_paciente_tipopaciente1_idx` (`tipopaciente_idTipoPaciente` ASC) VISIBLE,
  INDEX `fk_paciente_procedencia1_idx` (`procedencia_idProcedencia` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_destino1`
    FOREIGN KEY (`destino_idDestino`)
    REFERENCES `treage`.`destino` (`idDestino`),
  CONSTRAINT `fk_paciente_medico1`
    FOREIGN KEY (`medico_idMedico`)
    REFERENCES `treage`.`medico` (`idMedico`),
  CONSTRAINT `fk_paciente_motivoatencion1`
    FOREIGN KEY (`motivoatencion_idMotivoAtencion`)
    REFERENCES `treage`.`motivoatencion` (`idMotivoAtencion`),
  CONSTRAINT `fk_paciente_procedencia1`
    FOREIGN KEY (`procedencia_idProcedencia`)
    REFERENCES `treage`.`procedencia` (`idProcedencia`),
  CONSTRAINT `fk_paciente_tipopaciente1`
    FOREIGN KEY (`tipopaciente_idTipoPaciente`)
    REFERENCES `treage`.`tipopaciente` (`idTipoPaciente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `treage`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treage`.`ingreso` (
  `idIngreso` INT(11) NOT NULL AUTO_INCREMENT,
  `Valor` VARCHAR(45) NULL DEFAULT NULL,
  `paciente_idPaciente` INT(11) NOT NULL,
  `criterio_idCriterio` INT(11) NOT NULL,
  PRIMARY KEY (`idIngreso`),
  INDEX `fk_ingreso_paciente1_idx` (`paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_ingreso_criterio1_idx` (`criterio_idCriterio` ASC) VISIBLE,
  CONSTRAINT `fk_ingreso_criterio1`
    FOREIGN KEY (`criterio_idCriterio`)
    REFERENCES `treage`.`criterio` (`idCriterio`),
  CONSTRAINT `fk_ingreso_paciente1`
    FOREIGN KEY (`paciente_idPaciente`)
    REFERENCES `treage`.`paciente` (`idPaciente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
